Document: ts7820-utils
Title: Debian ts7820-utils Manual
Author: <insert document author here>
Abstract: This manual describes what ts7820-utils is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ts7820-utils/ts7820-utils.sgml.gz

Format: postscript
Files: /usr/share/doc/ts7820-utils/ts7820-utils.ps.gz

Format: text
Files: /usr/share/doc/ts7820-utils/ts7820-utils.text.gz

Format: HTML
Index: /usr/share/doc/ts7820-utils/html/index.html
Files: /usr/share/doc/ts7820-utils/html/*.html
